version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      target: build
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_API_URL=http://backend:8888
    depends_on:
      - backend
    networks:
      - napitochki-network

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888

networks:
  napitochki-network:
    driver: bridge